# Generated by Django 2.2.12 on 2020-06-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='uf',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
    ]
