# Generated by Django 2.2.12 on 2020-06-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planilha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('arquivo', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
    ]
